### ISSUE TITLE
Display recently captured PageFreezer scrapes

### ISSUE THREAD

**Issue by agillette** [edgi-govdata-archiving/webdiff-ui#2]
As an editor I want to be able to quickly see the most recently updated pages from PageFreezer.

**Comment by dcwalk** [comment]
This issue has been taken up in https://github.com/edgi-govdata-archiving/web-monitoring-ui! I'm going to close this out as development on the Web Monitoring project has moved ahead quite a bit (see https://github.com/edgi-govdata-archiving/web-monitoring for progress and current implementation)
