### ISSUE TITLE
Side-by-side diff visualizations

### ISSUE THREAD

**Issue by agillette** [edgi-govdata-archiving/webdiff-ui#3]
As a user I want to be able to see side-by-side comparisons of two different scrapes of the same URL from PageFreezer.

**Comment by dcwalk** [comment]
This issue has been taken up in https://github.com/edgi-govdata-archiving/web-monitoring-ui! I'm going to close this out as development on the Web Monitoring project has moved ahead quite a bit (see https://github.com/edgi-govdata-archiving/web-monitoring for progress and current implementation)
