### ISSUE TITLE
Link to most recent diff for any URL

### ISSUE THREAD

**Issue by agillette** [edgi-govdata-archiving/webdiff-ui#4]
As a user I want to be able to quickly access the most recent side-by-side diff for any URL from PageFreezer. The most recent diff means comparing the most recently scraped version of the site with the next most recent.

**Comment by dcwalk** [comment]
This issue has been taken up in https://github.com/edgi-govdata-archiving/web-monitoring-ui! I'm going to close this out as development on the Web Monitoring project has moved ahead quite a bit (see https://github.com/edgi-govdata-archiving/web-monitoring for progress and current implementation)
