### ISSUE TITLE
Link to oldest historical diff for any URL

### ISSUE THREAD

**Issue by agillette** [edgi-govdata-archiving/webdiff-ui#5]
As a user I want to be able to quickly compare the most recent scrape of any URL with the oldest available scrape of that URL from PageFreezer.

**Comment by dcwalk** [comment]
This issue has been taken up in https://github.com/edgi-govdata-archiving/web-monitoring-ui! I'm going to close this out as development on the Web Monitoring project has moved ahead quite a bit (see https://github.com/edgi-govdata-archiving/web-monitoring for progress and current implementation)
