### ISSUE TITLE
more detail on acquiring diffs?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/webdiff-ui#6]
Can you document in more detail how to get access to a diff? I only get four-oh-fours when clicking on the diff view pages; does the differ service need to be up and running, and/or are there other requirements?

**Comment by agillette** [comment]
We're working on containerizing everything. At the moment they don't talk to each other.

**Comment by dcwalk** [comment]
This has been done elsewhere! I'm going to close this out as development on the Web Monitoring project has moved ahead quite a bit (see https://github.com/edgi-govdata-archiving/web-monitoring for progress and current implementation)
