### ISSUE TITLE
move into "pagefreezer-cli"?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/webdiff-ui#7]
We'd like to bring all of the web mointoring tos into a single repo, which we will rename (https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/23). How would you feel about moving this work into that repo,, maybe also co-ordinating with other people doing similar work?

**Comment by titaniumbones** [comment]
@agillette  have you been thinking about this stuff at all? Have you seen some of the stuff that's happening in https://github.com/edgi-govdata-archiving/web-monitoring ?

**Comment by dcwalk** [comment]
This isn't needed any more! I'm going to close this out as development on the Web Monitoring project has moved ahead quite a bit (see https://github.com/edgi-govdata-archiving/web-monitoring for progress and current implementation)
